include"math.fbs";
include"meta.fbs";

namespace Arcadia.Serialization;

struct vertex{
    coord:vec3;
    normal:vec3;
    tex_coord:vec2;
}
table mesh{
    name:string;

    vertices:[vertex];
    elements:[uint];

    material_name:string;
}

struct pixel{
    red:float;
    green:float;
    blue:float;
    alpha:float;
}
table cubemap{
    name:string;

    pos_x_pixels:[pixel];
    neg_x_pixels:[pixel];
    pos_y_pixels:[pixel];
    neg_y_pixels:[pixel];
    pos_z_pixels:[pixel];
    neg_z_pixels:[pixel];
    size:uvec2;
}
table texture2d{
    name:string;

    pixels:[pixel];
    size:uvec2;
}
table material{
    name:string;

    ambient_texture2d_names:[string];
    diffuse_texture2d_names:[string];
    specular_texture2d_names:[string];
}

table skybox{
    name:string;

    mesh_name:string;
    cubemap_name:string;
}

table model{
    name:string;

    location:vec3;
    rotation:vec3;
    scale:vec3;
    pivot:vec3;

    mesh_names:[string];
}

table camera{
    name:string;

    pos:vec3;
    target:vec3;
    up:vec3;
    near_plane:float;
    far_plane:float;
    fovy:float;
    fovy_min:float;
    fovy_max:float;
    speed:float;
    viewport_size:uvec2;
    fixed_up:bool;
    up_epsilon:float;
    cursor_move_offset_range:vec2;
}

